version: '3'

services:
  

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DB_URL=postgresql+asyncpg://postgres:password@db:5432/postgres
    depends_on:
      - db
    volumes:
      - .:/app
    command: python main.py

volumes:
  postgres_data:
